"""POST /chat/{case_id} — context-aware chat grounded in case + diagnosis data."""

import json
import uuid

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth import UserQuota, consume_user_request_quota
from app.database import get_db
from app.models.db_models import Case, DiagnosisOutput
from app.models.schemas import ChatRequest, ChatResponse
from app.services.llm_service import llm_service

router = APIRouter(prefix="/chat", tags=["chat"])

_SYSTEM_TEMPLATE = """You are a clinical decision-support assistant helping a clinician interpret a differential diagnosis generated by an AI system.

You have full context of the patient case and the AI-generated diagnosis below. Answer questions clearly and concisely. Always remind the user that AI outputs are not a substitute for clinical judgement.

--- PATIENT CASE ---
{case_context}

--- AI DIAGNOSIS ---
{diagnosis_context}

Rules:
- Be factual and grounded in the evidence provided.
- If asked something outside the case context, say so clearly.
- Never fabricate lab values, diagnoses, or clinical facts not present above.
- Always include: "This is AI-generated decision support, not a medical diagnosis."
"""


def _build_case_context(case: Case) -> str:
    symptoms = case.symptoms.get("items", []) if isinstance(case.symptoms, dict) else []
    lines = [
        f"Symptoms: {', '.join(symptoms) or 'None recorded'}",
        f"Vitals: {json.dumps(case.vitals or {})}",
        f"History: {json.dumps(case.history or {})}",
        f"Labs: {json.dumps(case.labs or {})}",
    ]
    return "\n".join(lines)


def _build_diagnosis_context(outputs: list[DiagnosisOutput]) -> str:
    stage_map: dict[str, DiagnosisOutput | None] = {"initial": None, "reflection": None, "final": None}
    for row in outputs:
        if row.stage in stage_map:
            stage_map[row.stage] = row

    parts = []
    for stage, row in stage_map.items():
        if not row:
            continue
        diagnoses = row.diagnosis.get("diagnoses", [])
        dx_text = "; ".join(
            f"{d['condition']} [{d.get('confidence','?')}]"
            for d in diagnoses
        )
        parts.append(f"{stage.capitalize()} diagnosis: {dx_text}")
        if row.reasoning:
            parts.append(f"{stage.capitalize()} reasoning: {row.reasoning[:400]}")
    return "\n".join(parts) or "No diagnosis available yet."


@router.post("/{case_id}", response_model=ChatResponse)
async def chat(
    case_id: uuid.UUID,
    payload: ChatRequest,
    quota: UserQuota = Depends(consume_user_request_quota),
    db: AsyncSession = Depends(get_db),
):
    """Answer a question grounded in the stored case and diagnosis context."""
    case_result = await db.execute(select(Case).where(Case.id == case_id))
    case = case_result.scalar_one_or_none()
    if not case:
        raise HTTPException(status_code=404, detail=f"Case {case_id} not found")

    outputs_result = await db.execute(
        select(DiagnosisOutput)
        .where(DiagnosisOutput.case_id == case_id)
        .order_by(DiagnosisOutput.created_at)
    )
    outputs = outputs_result.scalars().all()

    system_prompt = _SYSTEM_TEMPLATE.format(
        case_context=_build_case_context(case),
        diagnosis_context=_build_diagnosis_context(list(outputs)),
    )

    messages = [{"role": "system", "content": system_prompt}]
    for msg in payload.messages:
        messages.append({"role": msg.role, "content": msg.content})

    try:
        result = await llm_service.chat_messages(messages, temperature=0.3, max_tokens=600)
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"LLM error: {exc}") from exc

    return ChatResponse(
        reply=result["reply"],
        usage=result["usage"],
        remaining_requests=quota.remaining_requests,
    )
